export const services = [
  {
    id: 1,
    num: "01",
    title: "Estudios Eléctricos Especializados",
    desc: "Análisis de sistemas eléctricos en BT, MT y AT. Diseño de redes, cálculos de cortocircuito, coordinación de protecciones, estudios de arc flash y flujo de carga.",
    tags: ["Cortocircuito", "Arc Flash", "Coordinación", "Flujo de Carga"],
    img: "/images/hero.jpg",
    fullDesc: "Realizamos estudios eléctricos completos para garantizar la seguridad y eficiencia de tus instalaciones. Incluye análisis de cortocircuito, coordinación de protecciones, estudios de arc flash, flujo de carga y calidad de energía. Nuestros informes cumplen con las normativas peruanas e internacionales.",
  },
  {
    id: 2,
    num: "02",
    title: "Subestaciones Eléctricas",
    desc: "Diseño, montaje y puesta en servicio de subestaciones de media tensión. Incluye celdas, transformadores y sistemas de control y protección.",
    tags: ["MT", "Transformadores", "Celdas", "Protecciones"],
    img: "/images/subestacion.jpg",
    fullDesc: "Diseñamos y construimos subestaciones eléctricas de media tensión llave en mano. Desde la ingeniería conceptual hasta la puesta en servicio, incluyendo celdas de media tensión, transformadores de potencia, sistemas de control, protecciones y obras civiles asociadas.",
  },
  {
    id: 3,
    num: "03",
    title: "Mantenimiento Eléctrico Industrial",
    desc: "Mantenimiento predictivo, preventivo y correctivo de instalaciones eléctricas industriales. Termografía, análisis de aceite y rigidez dieléctrica.",
    tags: ["Termografía", "Predictivo", "Correctivo", "Aceite Dieléctrico"],
    img: "/images/ingeniero.jpg",
    fullDesc: "Ofrecemos programas de mantenimiento eléctrico integral para la industria. Servicios de termografía infrarroja, análisis de aceite dieléctrico, medición de rigidez dieléctrica, mantenimiento de subestaciones, tableros eléctricos y sistemas de puesta a tierra.",
  },
  {
    id: 4,
    num: "04",
    title: "Redes Eléctricas y Tendidos",
    desc: "Diseño y construcción de redes de distribución aéreas y subterráneas. Instalación de postes, cableado y acometidas domiciliarias e industriales.",
    tags: ["Aéreas", "Subterráneas", "Acometidas", "Distribución"],
    img: "/images/tendido.jpg",
    fullDesc: "Ejecutamos proyectos de redes eléctricas de distribución primaria y secundaria, tanto aéreas como subterráneas. Instalación de postes de concreto y metálicos, tendido de conductores, montaje de subestaciones de distribución y acometidas para clientes residenciales, comerciales e industriales.",
  },
  {
    id: 5,
    num: "05",
    title: "Instalaciones Comerciales e Industriales",
    desc: "Proyectos llave en mano para instalaciones eléctricas en locales comerciales, edificios corporativos y plantas industriales.",
    tags: ["Comercial", "Industrial", "Llave en Mano", "Edificios"],
    img: "/images/industrial2.jpg",
    fullDesc: "Desarrollamos proyectos eléctricos integrales para el sector comercial e industrial. Incluye diseño de instalaciones, canalizaciones, tableros de distribución, sistemas de iluminación, fuerza motriz, sistemas de emergencia y puesta a tierra. Proyectos llave en mano con total garantía.",
  },
  {
    id: 6,
    num: "06",
    title: "Sistemas de Puesta a Tierra",
    desc: "Diseño, construcción y mantenimiento de sistemas de puesta a tierra. Mediciones de resistividad, diseño de mallas y mantenimiento correctivo.",
    tags: ["Mallas", "Resistividad", "PAT", "Mantenimiento"],
    img: "/images/grounding.jpg",
    fullDesc: "Especialistas en sistemas de puesta a tierra para todo tipo de instalaciones. Realizamos estudios de resistividad del suelo, diseño de mallas de tierra, cálculo de electrodos, instalación de sistemas PAT y mediciones periódicas de mantenimiento. Cumplimos con el Código Nacional de Electricidad.",
  },
  {
    id: 7,
    num: "07",
    title: "Levantamiento de Observaciones INDECI e ITSE",
    desc: "Asesoría técnica integral para el levantamiento de observaciones de INDECI e ITSE. Regularización de licencias y certificaciones de seguridad.",
    tags: ["INDECI", "ITSE", "Licencias", "Regularización"],
    img: "/images/panel.jpg",
    fullDesc: "Brindamos asesoría técnica y ejecución de trabajos para el levantamiento de observaciones realizadas por INDECI e ITSE. Incluye adecuación de instalaciones eléctricas, sistemas de protección contra incendios, señalización de seguridad y tramitación de licencias de funcionamiento.",
  },
];

const products = [
  { id: 1, name: "Interruptores Diferenciales", cat: "automatizacion", catName: "Automatización Industrial", img: "/images/prod-breaker.jpg", desc: "Protección diferencial para instalaciones eléctricas residenciales e industriales." },
  { id: 2, name: "Interruptores Termomagnéticos", cat: "automatizacion", catName: "Automatización Industrial", img: "/images/prod-breaker.jpg", desc: "Alta capacidad de ruptura para tableros de distribución general." },
  { id: 3, name: "Bandeja Portacable Perforada", cat: "bandeja", catName: "Bandeja Portacable", img: "/images/prod-tray.jpg", desc: "Ventilación natural para tendido ordenado de cables eléctricos." },
  { id: 4, name: "Bandeja Portacables Escalera", cat: "bandeja", catName: "Bandeja Portacable", img: "/images/prod-tray.jpg", desc: "Soporte robusto para cables de gran sección y peso." },
  { id: 5, name: "Cable N2XOH 0.6/1KV", cat: "conductores", catName: "Conductores Eléctricos", img: "/images/prod-cable.jpg", desc: "Libre de halógenos, de 4mm² a 500mm² para BT." },
  { id: 6, name: "Cable NH-80 450/750V", cat: "conductores", catName: "Conductores Eléctricos", img: "/images/prod-cable.jpg", desc: "Para interiores, de 2.5mm² a 10mm²." },
  { id: 7, name: "Cable N2XSY 18/30 kV", cat: "conductores", catName: "Conductores Eléctricos", img: "/images/prod-cable.jpg", desc: "Media tensión, de 50mm² a 630mm²." },
  { id: 8, name: "Arnés y Línea de Vida", cat: "proteccion", catName: "Equipos de Protección", img: "/images/prod-harness.jpg", desc: "Equipo completo para trabajos seguros en altura." },
  { id: 9, name: "Cascos y Lentes de Seguridad", cat: "proteccion", catName: "Equipos de Protección", img: "/images/prod-helmet.jpg", desc: "Dieléctricos con protección visual integral." },
  { id: 10, name: "Equipos de Protección Colectiva", cat: "proteccion", catName: "Equipos de Protección", img: "/images/prod-safety.jpg", desc: "Conos, barreras, señales para zonas de trabajo." },
  { id: 11, name: "Ropa de Trabajo Industrial", cat: "proteccion", catName: "Equipos de Protección", img: "/images/prod-workwear.jpg", desc: "Ignífuga, antiestática y de alta visibilidad." },
  { id: 12, name: "Barrillas de Cobre para PAT", cat: "tierra", catName: "Puesta a Tierra", img: "/images/prod-copper.jpg", desc: "Electrodos de cobre puro para sistemas de puesta a tierra." },
  { id: 13, name: "Bentonita Sódica", cat: "tierra", catName: "Puesta a Tierra", img: "/images/prod-ground.jpg", desc: "Mejorador de resistividad del suelo, bolsa 30kg." },
  { id: 14, name: "Caja de Concreto para PAT", cat: "tierra", catName: "Puesta a Tierra", img: "/images/prod-junction.jpg", desc: "Cajas de registro y inspección para puesta a tierra." },
  { id: 15, name: "Tablero Autosoportado", cat: "tableros", catName: "Tableros Eléctricos", img: "/images/prod-panel.jpg", desc: "Para distribución industrial de alta capacidad." },
  { id: 16, name: "Tablero de Distribución", cat: "tableros", catName: "Tableros Eléctricos", img: "/images/prod-panel.jpg", desc: "Empotrados y adosados para instalaciones comerciales." },
  { id: 17, name: "Tubería Conduit EMT", cat: "tuberias", catName: "Tuberías Eléctricas", img: "/images/prod-conduit.jpg", desc: "Metálica de pared delgada para instalaciones a la vista." },
  { id: 18, name: "Tubería Conduit Flexible", cat: "tuberias", catName: "Tuberías Eléctricas", img: "/images/prod-conduit.jpg", desc: "Para conexiones con vibración y movimiento." },
  { id: 19, name: "Tubería Conduit PVC", cat: "tuberias", catName: "Tuberías Eléctricas", img: "/images/prod-conduit.jpg", desc: "PVC corrugada y lisa para diversas aplicaciones." },
  { id: 20, name: "Accesorios para Tuberías", cat: "tuberias", catName: "Tuberías Eléctricas", img: "/images/prod-conduit.jpg", desc: "Conectores, curvas, uniones y derivaciones." },
];

export const categories = [
  { id: "all", name: "Todos los Productos" },
  { id: "automatizacion", name: "Automatización Industrial" },
  { id: "bandeja", name: "Bandeja Portacable" },
  { id: "conductores", name: "Conductores Eléctricos" },
  { id: "proteccion", name: "Equipos de Protección" },
  { id: "tierra", name: "Puesta a Tierra" },
  { id: "tableros", name: "Tableros Eléctricos" },
  { id: "tuberias", name: "Tuberías Eléctricas" },
];

export default products;
